apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: raiden20/gallery_backend:1.1
          name: backend
          envFrom:
            - configMapRef:
                name: backend-configmap
          ports:
            - containerPort: 8000