apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - image: quay.io/keycloak/keycloak:24.0
          name: keycloak
          command: ["/opt/keycloak/bin/kc.sh"]
          args: ["start-dev"]
          envFrom:
            - configMapRef:
                name: keycloak-configmap
          ports:
            - containerPort: 8080