kind: ConfigMap
apiVersion: v1
metadata:
  name: frontend-configmap
data:
  KEYCLOAK_CLIENT_ID: frontend
  KEYCLOAK_CLIENT_SECRET: sngzklG22OmHwnhmz8OqBVGfw4UkY7cH
  KEYCLOAK_ISSUER: http://keycloak-service:8080/realms/online_gallery
  NEXTAUTH_URL: http://localhost:3000
  NEXTAUTH_SECRET: my-own-secret-189656-haha
  END_SESSION_URL: http://keycloak-service:8080/realms/online_gallery/protocol/openid-connect/logout
  REFRESH_TOKEN_URL: http://keycloak-service:8080/realms/online_gallery/protocol/openid-connect/token