apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  ports:
    - name: server
      port: 9000
      targetPort: 9000
    - name: gui
      port: 9001
      targetPort: 9001
  selector:
    app: minio
  type: ClusterIP